- name: install gpg
  apt:
    name: gnupg,software-properties-common
    state: present
    update_cache: yes
    cache_valid_time: 3600
  when: ansible_distribution == "Ubuntu"

- name: add gpg key
  apt_key:
    url: "https://packages.grafana.com/gpg.key"
    validate_certs: no
  when: ansible_distribution == "ubuntu"

- name: add repository
  apt_repository:
    repo: "deb https://packages.grafana.com/oss/deb stable main"
    state: present
    validate_certs: no
  when: ansible_distribution == "Ubuntu"

- name: install grafana for Ubuntu
  apt:
    name: grafana
    state: latest
    update_cache: yes
    cache_valid_time: 3600
  when: ansible_distribution == "Ubuntu"

- name: start service grafana-server
  systemd:
    name: grafana-server
    state: restarted
    enabled: yes
  when: ansible_distribution == "Ubuntu"

- name: wait for service up
  uri:
    url: "http://127.0.0.1:3000"
    status_code: 200
  register: __result
  until: __result.status == 200
  retries: 120
  delay: 1
  when: ansible_distribution == "Ubuntu"

- name: install grafana for centOS
  dnf:
    name: grafana
    state: latest
    update_cache: yes
  when: ansible_distribution == "CentOS"

- name: start service grafana-server
  systemd:
    name: grafana-server
    state: restarted
    enabled: yes
  when: ansible_distribution == "CentOS"
