- name: Import InfluxDB GPG signing key
  apt_key: url=https://repos.influxdata.com/influxdb.key state=present
  when: ansible_distribution == "Ubuntu"

- name: Install InfluxDB packages
  apt: name=influxdb state=present
  when: ansible_distribution == "Ubuntu"

- name: Start the InfluxDB service
  service: name=influxdb state=restarted
  when: ansible_distribution == "Ubuntu"

- name:  install influxdb
  dnf:
    name: influxdb
    state: latest
  when: ansible_distribution == "CentOS"
